num = (input('Digite um numero de quatro digitos: '))
print('Unidades: {}'.format(num[3]))
print('Dezenas: {}'.format(num[2]))
print('Centenas: {}'.format(num[1]))
print('Milhares: {}'.format(num[0]))