br19 = ('Palmeiras', 'Atlético-MG', 'Corinthians', 'São Paulo', 'Santos', 'Flamengo', 'Internacional', 'Bahia', 'Ceará', 'Goiás', 'Botafogo', 'Athlético-PR', 'Chapecoense', 'Fortaleza', 'Fluminense', 'Cruzeiro', 'CSA', 'Grêmio', 'Avaí', 'Vasco')
print('*************************************************************************************************************')
print('                                           \033[1;35mCLASSIFICAÇÃO BRASILEIRÃO 2019\033[m                    ')
print(br19)
print('\n***********************************************************************************************************')
print(f'\nOs 5 primeiros colocados são: \033[32m{br19[0:5]}\033[m')
print(f'\nNa zona de rabaixamento temos: \033[31m{br19[-4:]}\033[m')
print(f'\nLista de times em ordem alfabética: \n\033[36m{sorted(br19)}\033[m')
print(f'\nO São Paulo ocupa a {br19.index("São Paulo") + 1}ª posição nesse momento')